---
dependency:
  name: galaxy
  options:
    force: true
    ignore-certs: false
    ignore-errors: false
driver:
  name: digitalocean
lint:
  name: yamllint
platforms:
  - name: molecule-focal-test-cardano-node-role-testnet-src
    image_id: ubuntu-20-04-x64
    region_id: ams3
    size_id: c-8
    groups:
      - all
      - testnet
      - from_src
provisioner:
  name: ansible
  config_options:
    defaults:
      bin_ansible_callbacks: true
      forks: 50
      internal_poll_interval: 0.001
      stdout_callback: yaml
      callback_whitelist: profile_tasks
      strategy: free
    ssh_connection:
      pipelining: true
  lint:
    name: ansible-lint
  playbooks:   # DRY playbooks by reusing what we can from the other scenario
    prepare: ../local-test-cardano-node-role/prepare.yml
    verify: ../local-test-cardano-node-role/verify.yml
  inventory:
    group_vars:
      from_src:
        cardano_install_method: src
      testnet:
        active_network: test

scenario:
  name: cloud-test-cardano-node-compilation-role
  test_sequence:
    - lint
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  directory: ../../tests/integration
  name: goss
  lint:
    name: yamllint
