---

- name: Libsodium | Checkout the project
  git:
    repo: "{{ libsodium_repo }}"
    dest: "{{ cardano_src_path }}/libsodium"
    force: true
    accept_hostkey: true

- name: Libsodium | Hydrate the install template
  template:
    src: libsodium.install.j2.bash
    dest: "{{ installation_scripts_path }}/libsodium.install.bash"
    mode: "a+x"

- name: Libsodium | Execute the install script
  command: "{{ installation_scripts_path }}/libsodium.install.bash"
  args:
    creates: /usr/local/lib/libsodium.a
