---

- name: Verify
  hosts: all
  become: true
  tasks:
    - include_vars: verify_vars.yml
    - include: install_goss.yml
    - include: ../../tests/test_ansible_all.yml
    - include: verify_goss_group.yml
      vars:
        goss_test_group: "all"
