---
goss_version: v0.3.7
goss_arch: amd64
goss_bin: /usr/local/bin/goss
goss_sha256sum: 357f5c7f2e7949b412bce44349cd32ab19eb3947255a8ac805f884cc2c326059.
goss_test_directory: /tmp/molecule/goss
goss_format: documentation
public_ip: "{{ ansible_eth0.ipv4.address }}"

cardano_listen_addr: 127.0.0.1
cardano_listen_port: 22322
cardano_service_name: cardano-node
cardano_node_wanted_version: 1.33.0
cardano_home_directory: /home/cardano
cardano_bin_path: "{{ cardano_home_directory }}/bin"
cardano_node_socket: "{{ cardano_node_runtime }}/db/node.socket"
cardano_node_runtime: "{{ cardano_home_directory }}/cardano_node"

cardano_wallets_path: wallets
cardano_testing_wallet: default
cardano_wallet_fullpath: "{{ cardano_home_directory }}/{{ cardano_wallets_path }}/{{ cardano_testing_wallet }}"

cardano_vkey_file: payment.vkey
cardano_skey_file: payment.skey
cardano_payment_addr_file: payment.addr

cardano_user: cardano

#  cardano_assets_siege: true - one off test against transaction sizes etc. a WIP generally TBD.
