---
dependency:
  name: galaxy
  options:
    force: true
    ignore-certs: false
    ignore-errors: false
driver:
  name: digitalocean
lint:
  name: yamllint
platforms:
  - name: molecule-focal-test-cardano-wallet-creation-ops
    region_id: ams3
    size_id: s-4vcpu-8gb
    groups:
      - all
      - wallet_holders
      - policy_holders
      - asset_holders
      - mature  # because the node is almost synced

provisioner:
  name: ansible
  config_options:
    defaults:
      bin_ansible_callbacks: true
      forks: 50
      internal_poll_interval: 0.001
      stdout_callback: yaml
      callback_whitelist: profile_tasks
      strategy: free
    ssh_connection:
      pipelining: true
  lint:
    name: ansible-lint
  playbooks:   # DRY playbooks by reusing what we can from the other scenario
    prepare: ../local-test-cardano-node-role/prepare.yml
    verify: ../local-test-cardano-node-role/verify.yml
  inventory:
    group_vars:
      all:
        cardano_install_method: dist
        active_network: test
        network_magic: 1097911063
        cardano_wallets:
          - &wallet_default default
          - wallet1
          - wallet2
        cardano_assets:
          - name: &test_asset TestAsset001
            quantity: &test_asset_qty 10000
            wallet: *wallet_default
          - name: &test_asset_2 TestAsset002
            quantity: &test_asset_qty_2 20000
            wallet: *wallet_default
        cardano_assets_burn:  # needed to maintain idempotence when testing against the distrubuted system
          - name: *test_asset
            quantity: *test_asset_qty
            wallet: *wallet_default
          - name: *test_asset_2
            quantity: *test_asset_qty_2
            wallet: *wallet_default

scenario:
  name: cloud-test-cardano-wallet-creation-ops
  test_sequence:
    - lint
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  directory: ../../tests/integration
  name: goss
  lint:
    name: yamllint
