---

dependency:
    name: galaxy
    options:
        force: true
        ignore-certs: true
        ignore-errors: true
driver:
    name: lxd
lint:
    name: yamllint
platforms:
    - groups:
          - all
      name: test-cardano-node-focal
      nested: "false"
      privileged: "false"
      image: "ubuntu/focal/amd64"

    - groups:
          - all
      name: test-cardano-node-bionic
      nested: "false"
      privileged: "false"
      image: "ubuntu/bionic/amd64"

    - groups:
          - all
      name: test-cardano-node-bullseye
      nested: "false"
      privileged: "false"
      image: "debian/bullseye/amd64"

provisioner:
    config_options:
        defaults:
            bin_ansible_callbacks: true
            display_ok_hosts: false
            display_skipped_hosts: false
            forks: 50
            internal_poll_interval: 0.001
            stdout_callback: yaml
            callback_whitelist: profile_tasks
            strategy: free
        ssh_connection:
            pipelining: true
    env:
        ANSIBLE_ROLES_PATH:
            $ephemeral_directory/roles/:../../roles/
    lint:
        name: ansible-lint
    name: ansible
scenario:
    name: local-cardano-node-role
    destroy_sequence:
        - cleanup
        - destroy
verifier:
    directory: ../../tests
    name: goss
    lint:
        name: yamllint
