---

- name: Converge Cardano Node
  hosts: all

  roles:
    - shareable-ansible-toolkit/common_ssh
    - role: cardano-node-role
      cardano_node_version: 1.29.0
    # test upgrading
    - role: cardano-node-role
      cardano_node_version: 1.30.1
