---

- name: Ops | Create Native Assets
  cardano_native_asset:
    cardano_bin_path: "{{ cardano_bin_path }}"
    name: "{{ item.name }}"
    policy_name: "native_asset_{{ item.name }}_policy"
  become: true
  become_user: "{{ cardano_user }}"
  register: assets_results
  loop: "{{ cardano_assets }}"
