---

- name: Cardano | Make sure the main source-holding directory exists
  file:
    path: "{{ cardano_src_path }}"
    state: directory
    mode: '600'

- name: Cardano | Wrap version fetching
  block:
    - name: Cardano | Get the current cardano-cli version
      command: cardano-cli --version
      environment:
        PATH: "{{ cardano_bin_path }}/:{{ ansible_env.PATH }}"
        LD_LIBRARY_PATH: /usr/local/lib
        PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
      register: cardano_cli_output
      changed_when: false   # for idempodence

    - name: Cardano | Get the current cardano-node version
      command: cardano-node --version
      environment:
        PATH: "{{ cardano_bin_path }}/:{{ ansible_env.PATH }}"
        LD_LIBRARY_PATH: /usr/local/lib
        PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
      register: cardano_node_output
      changed_when: false   # for idempodence

    - name: Cardano | set concrete binary versions' facts
      set_fact:
        cardano_cli_current_version: "{{ cardano_cli_output.stdout | regex_search('[0-9]+\\.[0-9]+\\.[0-9]') }}"
        cardano_node_current_version: "{{ cardano_node_output.stdout | regex_search('[0-9]+\\.[0-9]+\\.[0-9]') }}"
  rescue:

    - name: Cardano | set empty binary versions' facts
      set_fact:
        cardano_cli_current_version: ""
        cardano_node_current_version: ""

- name: Cardano | Wrap the install process
  block:

    - name: "Cardano | Make sure the {{ cardano_bin_path }} directory exists"
      file:
        path: "{{ cardano_bin_path }}"
        state: directory
        owner: "{{ cardano_user }}"
        group: "{{ cardano_group }}"
        mode: '777'

    - include: install_src.cardano.yml
      when: cardano_install_method == "src"

    - include: install_dist.cardano.yml
      when: cardano_install_method == "dist"

    - name: Cardano | cardano-node ownership
      file:
        path: "{{ cardano_bin_path }}/cardano-node"
        owner: "{{ cardano_user }}"
        group: "{{ cardano_group }}"

    - name: Cardano | cardano-cli ownership
      file:
        path: "{{ cardano_bin_path }}/cardano-cli"
        owner: "{{ cardano_user }}"
        group: "{{ cardano_group }}"

  when:
    - cardano_cli_current_version != cardano_node_version
    - cardano_node_current_version != cardano_node_version

