---
- name: Cardano Src | Checkout the project
  git:
    repo: "{{ cardano_repo }}"
    dest: "{{ cardano_src_path }}/cardano-node"
    force: true
    accept_hostkey: true
    version: "{{ cardano_node_version }}"

- name: Cardano Src | Hydrate the install template
  template:
    src: cardano.install.j2.bash
    dest: "{{ installation_scripts_path }}/cardano.install.bash"
    mode: "a+x"

- name: Cardano Src | Execute the install script
  shell: >
    {{ installation_scripts_path }}/cardano.install.bash
  async: "{{ 3600 * 4 }}"  # wait for up to 4 hours for the compilation to complete
  poll: 0
  register: cardano_install
  changed_when: false

- name: Cardano Src | Check if install is completed
  async_status:
    jid: "{{ cardano_install.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 120  # 4 hours in total, to keep in unison with the async task
  delay: 120

- name: Cardano Src | Make sure the service is stopped before we start changing it's binaries
  service:
    name: "{{ cardano_service_name }}.service"
    state: stopped
  ignore_errors: true  # if it's a first run or not installed, the service won't be there. TODO: evade that better!

- name: Cardano Src | install cardno-node bin
  shell: >
    cp -p "$(./scripts/bin-path.sh cardano-node)" {{ cardano_bin_path }}
  args:
    chdir: "{{ cardano_src_path }}/cardano-node"
  changed_when: cardano_node_current_version != cardano_node_version

- name: Cardano Src | install cardno-cli bin
  shell: >
    cp -p "$(./scripts/bin-path.sh cardano-cli)" {{ cardano_bin_path }}
  args:
    chdir: "{{ cardano_src_path }}/cardano-node"
  changed_when: cardano_cli_current_version != cardano_node_version

- name: Cardano Src | Cleanup sources
  file:
    path: "{{ cardano_src_path }}/cardano-node"
    state: absent
