---

- include: user.yml
- include: dependencies.yml
- include: build.libsodium.yml
  when: cardano_node_with_libsodium is true
- include: build.cardano.yml

- include: service.cardano.yml
  when: active_network != 'dev' and cardano_node_as_service is true

- include: service.cardano.devnet.yml
  when: active_network == 'dev' and cardano_node_as_service is true

- include: tools.cncli.yml
  when: cncli_add
