---

name: CD

on:
  workflow_run:
    workflows: ["Publish | Ansible Galaxy"]
    types:
      - completed

jobs:
  ci-test:
    # it's a test suite, however ran within a production environment in terms of infra etc.
    environment: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('cloud-requirements.txt') }}

      - uses: actions/cache@v2
        with:
          path: /tmp/molecule_ephemeral
          key: molecule_ephemeral

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r cloud-requirements.txt

      - name: Create molecule cache foder
        run: mkdir -p /tmp/molecule_ephemeral

      - name: Test with molecule
        run: molecule converge --scenario-name cloud-prod-cardano-node
        env:
          DO_API_KEY: ${{ secrets.DO_INFRA_KEY }}
          MOLECULE_EPHEMERAL_DIRECTORY: /tmp/molecule_ephemeral
