---

name: CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish | Ansible Galaxy"]
    types:
      - completed

jobs:
  cd-build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('cloud-requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r cloud-requirements.txt

      - name: Create molecule cache foder
        run: mkdir -p /tmp/molecule_ephemeral

      - name: CD Converge
        run: molecule converge --scenario-name cloud-prod-cardano-node
        env:
          DO_API_KEY: ${{ secrets.DO_INFRA_KEY }}
          MOLECULE_EPHEMERAL_DIRECTORY: /tmp/molecule_ephemeral
