---

name: CI Ops

on:
  workflow_run:
    workflows: ["Ansible Lint"]
    branches: [main]
    types:
      - completed

jobs:
  ci-test-ops:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: ci
    concurrency: molecule_ops
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('cloud-requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r cloud-requirements.txt
      - name: Run unit Tests
        run: |
          python -m pytest tests

      - name: Create molecule cache foder
        run: mkdir -p /tmp/molecule_ephemeral/${{ github.run_id }}

      - name: Test with molecule
        run: molecule test --scenario-name cloud-test-cardano-ops
        env:
          DO_API_KEY: ${{ secrets.DO_INFRA_KEY }}
          TESTNET_SNAPSHOT_NAME: ${{ secrets.TESTNET_SNAPSHOT_NAME }}
          MOLECULE_EPHEMERAL_DIRECTORY: /tmp/molecule_ephemeral/${{ github.run_id }}
