---

name: CI Sources

on:
  workflow_run:
    # building sources is a long process, do it only after we have confirmed the general functionality works A OK
    workflows: ["CI Prebuilt"]
    branches: [main]
    types:
      - completed

jobs:
  ci-test-from-src:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: ci
    concurrency: molecule_src
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('cloud-requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r cloud-requirements.txt

      - name: Create molecule cache foder
        run: mkdir -p /tmp/molecule_ephemeral/${{ github.run_id }}

      - name: Test with molecule
        run: |
          molecule test --scenario-name cloud-test-cardano-node-compilation-role
        env:
          DO_API_KEY: ${{ secrets.DO_INFRA_KEY }}
          MOLECULE_EPHEMERAL_DIRECTORY: /tmp/molecule_ephemeral/${{ github.run_id }}
