---

name: CI

on:
  workflow_run:
    workflows: ["Ansible Lint"]
    branches: [main]
    types:
      - completed

jobs:
  ci-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('test-cloud-requirements.txt') }}

#      - name: Install dependencies
#        run: |
#          python3 -m pip install --upgrade pip
#          python3 -m pip install -r test-cloud-requirements.txt

      - name: Debugging
        env:
          NOT_SECRET: ${{ secrets.NOT_SECRET }}
        run: >-
          [ "$NOT_SECRET" = "not_secret" ] && echo "ok" || echo "not ok"

#      - name: Test with molecule
#        run: molecule test --scenario-name cloud-cardano-node-role
#        env:
#          DO_API_KEY: ${{ secrets.DO_INFRA_KEY }}
